a = int(12)
b = int(36)
print("value of a \"+\" b:",a+b)
print('"""""""Calculator"""""""')
a = int(input("enter a value:"))
b = int(input("enter b value:"))

print("Enter 1 for Addition")
print("Enter 2 for Substraction")
print("Enter 3 for Multiplication")
print("Enter 4 for Division")
print("Enter 5 for Floor operation")
print("Enter 6 for Modulo")
print("Enter 7 for Power operation")
#print("Choose the operation to be performed:")
c = input("choose the operation to perform:")
# if c==1:
print("value of a \"+\" b:",a+b)